web:
  image: vamsiammineni/web-app:latest
  command: python -u app.py
  ports:
    - "5000:5000"
  volumes:
    - .:/app
  links:
    - db
db:
  image: mongo:3.0.2
  ports:
    - 27017:27017
  command: mongod --smallfiles --logpath=/dev/null # --quiet